dhl_tracking.register:
    description: Start tracking a package
    fields:
        package_id:
            description: The ID of the package to track.
            example: "123456789"

dhl_tracking.unregister:
    description: Stop tracking a package
    fields:
        package_id:
            description: The ID of the package to stop tracking.
            example: "123456789"
